### ISSUE TITLE
Qiita のストック記事，Zenn のいいねした記事の混合が欲しい

### ISSUE THREAD

**Issue by YoshitakaNaraoka** [y4asse/chietta#196]
- ユーザーとして，「あーあの記事どっちだったかな……」 -> Qiita stock を開く，Zenn いいね を開く という 2 つの操作が発生している
 - 結果として何個もブラウザのタブが開かれるようになってしまい，Chietta の「色々なサイトを見て回る必要がなくなり、一つのサイトで簡単に情報収集をすることが」という趣旨から逸れた UX になってしまっている

**Comment by YoshitakaNaraoka** [comment]
要するにブックマーク機能だな……

**Comment by YoshitakaNaraoka** [comment]
#188 と被っているので立てておいてなんですが Close させていただきます．申し訳ありませんでした……

**Comment by y4asse** [comment]
@YoshitakaNaraoka  ご意見ありがとうございます！自分自身もQiitaとZennどっちで見たか忘れて両方見るみたいなことがあり、　#188  とは別でこの機能を作ろうと思っていたのでopenさせていただきます！
ですがQiitaやZennのAPIの仕様上実装できない可能性があるのでご了承ください ！

**Comment by YoshitakaNaraoka** [comment]
まさか Reopen されるとは思ってませんでした！
ありがとうございます！
僕も Chietta 良いサービスだと思ってるんでドシドシやっていきを発生させていってください！

**Comment by y4asse** [comment]
こちらのissueですが、色々調べた結果、Qiitaのいいねやストックを取得する方法がないことが分かったのでクローズさせていただきます。大変申し訳ありません 😭 
代わりに #188 を実装しましたので、こちらを使っていただけると幸いです！
